n = input('Digite algo: ')
print('N é do tipo? ',type(n))
print('N é alfanumerico? ' , n.isalnum())
print('N é alfabetico? ' , n.isalpha())
print('N está em letras maisculas? ' , n.isupper())
print('N é decimal? ' , n.isdecimal())
print('N é minusculo? ' , n.islower())
print('N é imprimivel? ' , n.isprintable())
print('N é espaço? ' , n.isspace())
print('N é numero? ' , n.isnumeric())
print('='*30)